apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Ingress
      name: ai-task-processing-platform-ingress
    patch: |-
      - op: replace
        path: /spec/ingressClassName
        value: nginx

images:
  - name: ritik799/ai-task-processing-platform-frontend
    newName: ritik799/ai-task-processing-platform-frontend
    newTag: d278d5e
  - name: ritik799/ai-task-processing-platform-backend
    newName: ritik799/ai-task-processing-platform-backend
    newTag: d278d5e
  - name: ritik799/ai-task-processing-platform-worker
    newName: ritik799/ai-task-processing-platform-worker
    newTag: d278d5e