apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ritik799/ai-task-processing-platform-frontend
    newName: ritik799/ai-task-processing-platform-frontend
    newTag: 22b8746
  - name: ritik799/ai-task-processing-platform-backend
    newName: ritik799/ai-task-processing-platform-backend
    newTag: 22b8746
  - name: ritik799/ai-task-processing-platform-worker
    newName: ritik799/ai-task-processing-platform-worker
    newTag: 22b8746